version: '3.9'

services:
  postgres:
    container_name: basic-postgres
    image: postgres
    env_file:
      postgres.env
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - /home/vladsal/socket_dir:/var/run/postgresql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - postgres.env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped
  
  web: 
   container_name: webservice
   build: ./app
   volumes:
   - ./app:/app
   ports:
    - '5000:5000'
   restart: unless-stopped
  tracker:
   container_name: tracker
   build: ./Yolov5_DeepSort_Pytorch
   volumes:
    - ./Yolov5_DeepSort_Pytorch:/Yolov5_DeepSort_Pytorch
   ports:
    - '5001:5001'
   restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: